// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIY-4QG5SYMZV-hhrgaOBpk2h_IRTCz7c',
    appId: '1:446805045923:web:1b43541b0967e31fb64516',
    messagingSenderId: '446805045923',
    projectId: 'imjang-catch-dev',
    authDomain: 'imjang-catch-dev.firebaseapp.com',
    storageBucket: 'imjang-catch-dev.appspot.com',
    measurementId: 'G-X6Y2VBWT2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoSxgxx2h6SkCCaKTWeytFKcw_CW2eDrg',
    appId: '1:446805045923:android:9f70e21f35b755fdb64516',
    messagingSenderId: '446805045923',
    projectId: 'imjang-catch-dev',
    storageBucket: 'imjang-catch-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCdL3NO7o_UyYTcCt09Kw9FEf62WGy6sc',
    appId: '1:446805045923:ios:5ea94e0fe53da7e8b64516',
    messagingSenderId: '446805045923',
    projectId: 'imjang-catch-dev',
    storageBucket: 'imjang-catch-dev.appspot.com',
    iosBundleId: 'com.gyeony.imjanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCdL3NO7o_UyYTcCt09Kw9FEf62WGy6sc',
    appId: '1:446805045923:ios:b9fe016571653cd1b64516',
    messagingSenderId: '446805045923',
    projectId: 'imjang-catch-dev',
    storageBucket: 'imjang-catch-dev.appspot.com',
    iosBundleId: 'com.gyeony.imjanger.RunnerTests',
  );
}
